version: '3.8'

services:
  backend:
    environment:
      - GIN_MODE=debug
    volumes:
      - ./backend:/app
      - /app/vendor
    command: go run main.go
    
  frontend:
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3000:3000"